Models/types/Vacation.cs
namespace WanderSnap.Models
{
    public class Vacation
    {
        public long id { get; set; }
        public long user { get; set; }
        public string name { get; set; }
        public string? description { get; set; }
        public DateTime start { get; set; }
        public DateTime end { get; set; }
        public string[] images { get; set; }
        public Vacation(long id, long user, string name, string? description, DateTime start, DateTime end, string[] images)
        {
            this.id = id;
            this.user = user;
            this.name = name;
            this.description = description;
            this.start = start;
            this.end = end;
            this.images = images;
        }

    }
}

Pages/profile/vacation/AddVacation.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WanderSnap.Models;
using WanderSnap.Models.DB.Primitives;

namespace WanderSnap.Pages;
[Authorize]
public class AddVacationModel : PageModel
{
    private DbHandler _DB = new DbHandler();
    private readonly ILogger<IndexModel> _logger;
    public bool _IsEditing = false;
    [BindProperty(SupportsGet = true)]
    public int? VacationId { get; set; }
    [BindProperty, Required(ErrorMessage = "Er is geen naam ingevuld")]
    public string form_VacationName { get; set; }
    [BindProperty]
    public string? form_VacationDescription { get; set; }
    [BindProperty, Required(ErrorMessage = "Er is geen startdatum ingevuld")]
    public DateTime form_StartDate { get; set; }
    [BindProperty, Required(ErrorMessage = "Er is geen einddatum ingevuld")]
    public DateTime form_EndDate { get; set; }
    public AddVacationModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }
    public IActionResult OnGet()
    {
        if (VacationId == null) return Page();
        var vacation = this._DB._Provider.select("Vacation",
            new string[] { "id", "name", "description", "start", "end" },
            new Where[] {
                new Where("id", Compare.Equal, VacationId.ToString()),
                new Where("User", Compare.Equal, User.Identity.Name)
        });
        if (vacation.Count() != 1) return Page();
        this._IsEditing = true;
        this.form_VacationName = vacation[0]._columns.Find(col => col._column == "name")._value;
        this.form_VacationDescription = vacation[0]._columns.Find(col => col._column == "description")._value;
        this.form_StartDate = DateTimeOffset.FromUnixTimeSeconds((long)vacation[0]._columns.Find(col => col._column == "start")._value).DateTime;
        this.form_EndDate = DateTimeOffset.FromUnixTimeSeconds((long)vacation[0]._columns.Find(col => col._column == "end")._value).DateTime;
        return Page();
    }
    public IActionResult OnPost()
    {
        if (!this.OnPostValidation())
            return Page();
        var data = new List<Column>();
        data.Add(new Column("name", this.form_VacationName));
        data.Add(new Column("User", User.Identity.Name));
        data.Add(new Column("start", new DateTimeOffset(this.form_StartDate.ToUniversalTime()).ToUnixTimeSeconds().ToString()));
        data.Add(new Column("end", new DateTimeOffset(this.form_EndDate.ToUniversalTime()).ToUnixTimeSeconds().ToString()));
        if (this.form_VacationDescription != null)
            data.Add(new Column("description", this.form_VacationDescription));
        bool status;
        if (this.VacationId != null)
            status = this.OnPostUpdate(data);
        else
            status = this.OnPostInsert(data);

        if (!status)
            return Page();

        return RedirectToPage("/profile/Profile", null, new { Username = User.Identity.Name });
    }
    private bool OnPostInsert(List<Column> data)
    {
        return this._DB._Provider.insert("Vacation", data);
    }
    private bool OnPostUpdate(List<Column> data)
    {
        var vacation = this._DB._Provider.select("Vacation",
            new string[] { "id", "User" },
            new Where[] {
                new Where("id", Compare.Equal, VacationId.ToString()),
                new Where("User", Compare.Equal, User.Identity.Name)
        });
        if (vacation.Count() != 1)
        {
            ModelState.AddModelError("form_VacationName", "Deze vakantie bestaat niet");
            return false;
        }
        return this._DB._Provider.update("Vacation", data,
            new Where[] { new Where("id", Compare.Equal, this.VacationId.ToString()) },
        -1);
    }
    private bool OnPostValidation()
    {
        if (!ModelState.IsValid)
            return false;
        if (this.form_StartDate > this.form_EndDate)
        {
            ModelState.AddModelError("form_StartDate", "De startdatum mag niet later zijn dan de einddatum");
            return false;
        }

        return true;
    }
}

Pages/profile/vacation/Vacation.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WanderSnap.Models;
using WanderSnap.Models.api;
using System.ComponentModel.DataAnnotations;
namespace WanderSnap.Pages;
[Authorize]
public class VacationsModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;
    [BindProperty(SupportsGet = true)]
    public string Username { get; set; }
    [BindProperty(SupportsGet = true)]
    public int VacationId { get; set; }

    [BindProperty(SupportsGet = false), Required(ErrorMessage = "Please give a photo of the vacation")]
    public IFormFile form_photo { get; set; }
    [BindProperty(SupportsGet = false)]
    public DateTime form_date { get; set; }
    [BindProperty(SupportsGet = false), StringLength(255, ErrorMessage = "The description is too long")]
    public string? form_description { get; set; }
    private IWebHostEnvironment _environment;
    public bool _HasError = false;
    private DbHandler _DB = new DbHandler();
    public User _User;
    public Vacation _Vacation;
    public int _HowManyPhotos;
    public VacationsModel(IWebHostEnvironment environment, ILogger<IndexModel> logger)
    {
        _logger = logger;
        _environment = environment;
    }

    public IActionResult OnGet()
    {
        bool usesId = Int64.TryParse(Username, out long id);
        var user = this._DB._Provider.select("User",
        new string[] { "id", "username", "email", "description", "profile_picture", "created_at" },
        new Models.DB.Primitives.Where[] {
            usesId ?
            new Models.DB.Primitives.Where("id", Models.DB.Primitives.Compare.Equal, Username)
            : new Models.DB.Primitives.Where("username", Models.DB.Primitives.Compare.Equal, Username)
        });
        //if (usesId == false) return RedirectToPage("/profile/vacation/Vacation", null, new { Username = user[0]._columns.Find(col => col._column == "id")._value, VacationId = VacationId });
        if (user.Count() != 1) return RedirectToPage("/Index");

        DateTime start = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddSeconds(user[0]._columns.Find(col => col._column == "created_at")._value);
        this._User = new User(
            user[0]._columns.Find(col => col._column == "id")?._value,
            user[0]._columns.Find(col => col._column == "username")?._value,
            user[0]._columns.Find(col => col._column == "email")?._value,
            user[0]._columns.Find(col => col._column == "description")?._value,
            user[0]._columns.Find(col => col._column == "profile_picture")?._value,
            start
        );
        var vacation = this._DB._Provider.select("Vacation",
        new string[] { "id", "name", "description", "start", "end" },
        new Models.DB.Primitives.Where[] {
            new Models.DB.Primitives.Where("id", Models.DB.Primitives.Compare.Equal, VacationId.ToString())
        });
        if (vacation.Count() != 1) return RedirectToPage("/profile/Profile", null, new { Username = this._User.id });
        start = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddSeconds(vacation[0]._columns.Find(col => col._column == "start")?._value);
        this._Vacation = new Vacation(
            vacation[0]._columns.Find(col => col._column == "id")?._value,
            this._User.id,
            vacation[0]._columns.Find(col => col._column == "name")?._value,
            vacation[0]._columns.Find(col => col._column == "description")?._value,
            start,
            new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddSeconds(vacation[0]._columns.Find(col => col._column == "end")?._value),
            new string[] { }
        );
        this._HowManyPhotos = this._DB._Provider.count("Vacation_Photo", new Models.DB.Primitives.Where[] {
            new Models.DB.Primitives.Where("Vacation", Models.DB.Primitives.Compare.Equal, this._Vacation.id.ToString())
        });
        return Page();
    }

    [HttpPost]
    public IActionResult OnPostAddPhoto()
    {
        // validate input
        this._HasError = false;
        if (ModelState.IsValid == false)
        {
            this.OnGet();
            this._HasError = true;
            return Page();
        }
        var fileValidation = this.FileValidation(this.form_photo);
        if (fileValidation.status == false)
        {
            ModelState.AddModelError("form_photo", fileValidation.error);
            this.OnGet();
            this._HasError = true;
            return Page();
        }
        if (this.form_date > DateTime.UtcNow.AddDays(1))
        {
            ModelState.AddModelError("form_date", "The date cannot be in the future");
            this.OnGet();
            this._HasError = true;
            return Page();
        }
        // check if the vacation exists
        var vacation = this._DB._Provider.select("Vacation", null, new Models.DB.Primitives.Where[] {
            new Models.DB.Primitives.Where("id", Models.DB.Primitives.Compare.Equal, this.VacationId.ToString()),
            new Models.DB.Primitives.Where("User", Models.DB.Primitives.Compare.Equal, User.Identity.Name)
        });
        if (vacation.Count() < 1)
        {
            ModelState.AddModelError("form_photo", "The vacation does not exist");
            this.OnGet();
            this._HasError = true;
            return Page();
        }
        // check if the date is not earlier than the vacation start
        var vacationStart = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddSeconds(vacation[0]._columns.Find(col => col._column == "start")?._value);
        if (this.form_date < vacationStart)
        {
            ModelState.AddModelError("form_date", "The date cannot be earlier than the vacation start");
            this.OnGet();
            this._HasError = true;
            return Page();
        }
        // Check if the folder /uploads/profile/vacations exists and create it if it doesn't
        if(!Directory.Exists(Path.Combine(_environment.ContentRootPath, "wwwroot/uploads/profile/vacations")))
            Directory.CreateDirectory(Path.Combine(_environment.ContentRootPath, "wwwroot/uploads/profile/vacations"));
        // upload the file
        var fileName = "vacation_" + this.VacationId + "_photo_" + DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalSeconds + "." + this.form_photo.ContentType.Split("/")[1];
        var file = Path.Combine(_environment.ContentRootPath, "wwwroot/uploads/profile/vacations", fileName);
        using (var filestream = new FileStream(file, FileMode.Create))
        {
            this.form_photo.CopyTo(filestream);
        }
        // insert the photo
        var photo = this._DB._Provider.insert("Vacation_Photo", new Models.DB.Primitives.Column[] {
            new Models.DB.Primitives.Column("Vacation", this.VacationId.ToString()),
            new Models.DB.Primitives.Column("path", fileName),
            new Models.DB.Primitives.Column("description", this.form_description ?? ""),
            new Models.DB.Primitives.Column("date", this.form_date.ToUniversalTime().Subtract(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalSeconds.ToString())
        }.ToList());

        return RedirectToPage("/profile/vacation/Vacation", null, new { Username = this.Username, VacationId = this.VacationId });
    }
    private (string error, bool status) FileValidation(IFormFile file)
    {
        if (file == null) return (error: "Please give a photo of the vacation", status: false);
        if (file.Length > 1000000) return (error: "The photo is too big", status: false);
        if (file.ContentType != "image/jpeg" && file.ContentType != "image/png") return (error: "The photo is not a jpeg or png", status: false);
        return (error: "", status: true);
    }

    [HttpGet]
    public JsonResult OnGetVacations([FromQuery] ProfileGetVacations data)
    {
        // validate input
        var response = new ApiResponse<Image?>(false, "Nothing found", null);
        if (data == null) return new JsonResult(response);
        // check if the vacation for the user exists
        var vacationFetch = this._DB._Provider.select("Vacation", new string[] { "id" }, new Models.DB.Primitives.Where[] {
            new Models.DB.Primitives.Where("User", Models.DB.Primitives.Compare.Equal, this.Username),
            new Models.DB.Primitives.Where("id", Models.DB.Primitives.Compare.Equal, this.VacationId.ToString())
        }, 1);
        if (vacationFetch.Count() != 1)
        {
            return new JsonResult(response);
        }
        // get the photo
        var photoFetch = this._DB._Provider.select("Vacation_Photo", null, new Models.DB.Primitives.Where[] {
            new Models.DB.Primitives.Where("Vacation", Models.DB.Primitives.Compare.Equal, ((long) vacationFetch[0]._columns.Find(col => col._column == "id")._value).ToString()),
        }, 1, offset: data.which);
        // return the photo
        var vacation = new Image(
            photoFetch[0]._columns.Find(col => col._column == "id")?._value,
            photoFetch[0]._columns.Find(col => col._column == "description")?._value,
            photoFetch[0]._columns.Find(col => col._column == "path")?._value,
            new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).AddSeconds(photoFetch[0]._columns.Find(col => col._column == "date")?._value)
        );
        return response.CreateJsonResult(true, "Found", vacation);
    }
    public IActionResult OnPostDeletePhoto([FromBody] ProfileGetVacations data)
    {
        // validate input
        var response = new ApiResponse<Image?>(false, "Nothing found", null);
        if (data == null || data.which == null) return new JsonResult(response);
        // check if the vacation for the user exists
        var vacationFetch = this._DB._Provider.select("Vacation", new string[] { "id" }, new Models.DB.Primitives.Where[] {

Pages/profile/vacation/AddVacation.cshtml
@page "/profile/adventure/Add/{VacationId:int?}"
@model AddVacationModel
@{ ViewData["Title"] = "Vakantie toevoegen"; }

<section class="">
    <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        <a asp-page="Index" class="flex gap-3 items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white">
            <span><svg viewBox="0 0 15 15"
                    class="flex-shrink-0 w-6 h-6 text-yellow-400 transition duration-75 dark:text-yellow-600"
                    fill="currentColor" xmlns="http://www.w3.org/2000/svg" width="15" height="15">
                    <path
                        d="M7.5 1.5v-1m0 13.99v-.998m6-5.997h1m-13 0h-1m2-4.996l-1-1m12 0l-1 1m-10 9.993l-1 1m12 0l-1-1m-2-4.997a2.999 2.999 0 01-3 2.998 2.999 2.999 0 113-2.998z"
                        stroke="currentColor" stroke-linecap="square"></path>
                </svg> </span>
            <span>WanderSnap</span>
        </a>
        <div
            class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
            <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                    @if(@Model._IsEditing) {<span>Edit your </span>} else {<span>Add a </span>} extraordinary adventure
                </h1>
                <form class="space-y-4 md:space-y-6" method="post">
                    <div>
                        <label asp-for="form_VacationName"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Name:</label>
                        <input type="text" asp-for="form_VacationName"
                            class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="Adventure to ...">
                        <span asp-validation-for="form_VacationName" class="text-red-700"></span>
                    </div>
                    <div>
                        <label asp-for="form_VacationDescription"
                            class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description:</label>
                        <textarea asp-for="form_VacationDescription"
                            class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                            placeholder="I went together with ..."></textarea>
                        <span asp-validation-for="form_VacationDescription" class="text-red-700"></span>
                    </div>
                    <div>
                        <div class="flex">
                            <div class="w-full">
                                <label asp-for="form_StartDate"
                                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">From:</label>
                                <input value='@DateTime.Today.ToString("yyyy-MM-dd")' type="date"
                                    asp-for="form_StartDate"
                                    class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                            </div>
                            <div class="w-full">
                                <label asp-for="form_EndDate"
                                    class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">To:</label>
                                <input type="date" asp-for="form_EndDate"
                                    value='@DateTime.Today.AddDays(7).ToString("yyyy-MM-dd")'
                                    class="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                            </div>
                        </div>
                        <span class="text-red-700" asp-validation-for="form_StartDate"></span>
                        <span class="text-red-700" asp-validation-for="form_EndDate"></span>
                    </div>
                    <button type="submit" asp-validation-for="form_EndDate"
                        class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">@if(@Model._IsEditing)
                        {<span>Edit </span>} else {<span>Add </span>}
                        your WanderSnap adventure</button>
                </form>
            </div>
        </div>
    </div>
</section>

Pages/profile/vacation/Vacation.cshtml
@page "/profile/Profile/{Username}/adventure/{VacationId:int}"
@model VacationsModel
@{
ViewData["Title"] = "Vakantie naar " + Model._Vacation?.name;
}
@if (Model._User.id.ToString() == User.Identity.Name) {
<script src="~/js/vacation/deletePhoto.js" defer></script>
}
<script src="~/js/vacation/loadPhotos.js" defer></script>

<section class="flex relative">
    <div class="w-full m-2 mt-0 pt-2">
        <div class="flex flex-col md:flex-row md:space-x-4">
            <div class="flex flex-col w-full md:w-1/2">
                <div class="flex flex-col w-full">
                    <h1 class="text-2xl font-bold text-gray-800 dark:text-gray-100">
                        @Model._Vacation?.name
                    </h1>
                    <p class="text-gray-600 p-5 dark:text-gray-400">
                        @Model._Vacation?.description
                    </p>
                </div>
                <div class="flex flex-col w-full mt-4">
                    <h2 class="text-xl font-bold text-gray-800 dark:text-gray-100">
                        @Model._Vacation?.start.ToString("dd-MM-yyyy") -
                        @Model._Vacation?.end.ToString("dd-MM-yyyy")
                    </h2>
                </div>
            </div>
        </div>
    </div>
    @if (Model._User.id.ToString() == User.Identity.Name) {
    <div id="editProfile" class="absolute gap-1 flex flex-row bottom-2 right-1">
        <a asp-page="/profile/vacation/AddVacation" asp-route-VacationId="@Model._Vacation.id"
            class=" bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Edit
            adventure</a>
    </div>
    }
    <a class="btn btn-ghost" asp-page="/profile/Profile" asp-route-Username="@Model.Username">Back</a>
</section>
<hr />
@if (Model._User.id.ToString() == User.Identity?.Name) {
<section class="m-1 mt-2 flex justify-end">
    <button class="btn" onclick="AddPhotoModal.showModal()">Add foto</button>
    <dialog @(Model._HasError ? "open" : "" ) id="AddPhotoModal" class="modal">
        <div class="modal-box">
            <form method="dialog">
                <button for="my-modal-3" class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>

            </form>
            <h3 class="font-bold text-lg">Add a photo to the vacation</h3>
            <hr class="mt-1 mb-2" />
            <form method="post" enctype="multipart/form-data">
                <label class="label">
                    <span asp-for="form_photo" class="label-text">New photo</span>
                </label>
                <input asp-for="form_photo" type="file" class="file-input file-input-bordered w-full max-w-xs" />
                <label class="label">
                    <span asp-validation-for="form_photo" class="label-text-alt text-red-700"></span>
                </label>
                <label class="label">
                    <span asp-for="form_date" class="label-text">Date of photo </span>
                </label>
                <input value='@DateTime.Today.ToString("yyyy-MM-dd")' asp-for="form_date" type="date"
                    class="input input-bordered w-full max-w-xs" />
                <label class="label">
                    <span asp-validation-for="form_date" class="label-text-alt text-red-700"></span>
                </label>
                <label class="label">
                    <span asp-for="form_description" class="label-text">Description</span>
                </label>
                <textarea asp-for="form_description" class="textarea textarea-bordered resize-none w-full" rows="3"
                    placeholder="We went to..."></textarea>
                <label class="label">
                    <span asp-validation-for="form_description" class="label-text-alt text-red-700"></span>
                </label>
                <button asp-page-handler="AddPhoto" class="btn btn-primary mt-2">Add foto</button>
            </form>

        </div>
        <form method="dialog" class="modal-backdrop">
            <button class="cursor-default">close</button>
        </form>
    </dialog>
</section>
}
<section class="m-1">
    @if (Model._HowManyPhotos == 0) {
    <div class="flex justify-center">
        <p class="text-gray-600 dark:text-gray-400">There are no photos yet for this vacation
            @if(Model._User.id.ToString() == User.Identity?.Name) {<span>Add photos of your vacation to share with your
                family and friends!</span>}</p>
    </div>
    } else {
    <div class="flex justify-center">
        <div id="photos" class="gap-1 flex flex-wrap justify-center ">
            @for(var i = 0; i < Model._HowManyPhotos; i++) { <div class="h-min">
                <div role="loading"
                    class="space-y-8 max-w-[100vw] w-96 h-60 relative md:space-y-0  md:space-x-8 md:flex md:items-center">
                    <div
                        class="flex absolute items-center justify-center w-full h-full bg-gray-300 rounded sm:w-96 dark:bg-gray-700">
                        <div class="w-1/3 h-1/3">
                            <svg aria-hidden="true"
                                class="w-full h-full mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600"
                                viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                                    fill="currentColor" />
                                <path
                                    d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                                    fill="currentFill" />
                            </svg>
                            <span class="sr-only">Loading...</span>
                        </div>
                    </div>

                </div>
        </div>}
    </div>
    </div>
    }
</section>
@if (Model._User.id.ToString() == User.Identity.Name) {
<input type="hidden" value="True" id="isUser">
<section class="m-1 mt-2 flex justify-end">

    <dialog data-id="null" id="confirmDeleteModal" class="modal">
        <div class="modal-box">
            <form method="dialog">
                <button for="confirmDeleteModal"
                    class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">✕</button>
            </form>
            <h3 class="font-bold text-lg">Are you sure you want to delete this photo</h3>
            <p class="text-sm">This action cannot be undone</p>
            <div class="flex gap-3 justify-end mt-3">
                <form method="dialog">
                    <button class="btn btn-sm btn-ghost">Cancel</button>
                </form>
                <button id="confirmedDeleteButton"
                    class="bg-red-900 rounded-lg p-3 pt-1 pb-1 hover:bg-red-900/50 ">Delete</button>
            </div>

        </div>
        <form method="dialog" class="modal-backdrop">
            <button class="cursor-default">close</button>
        </form>
    </dialog>
</section>
}
@Html.AntiForgeryToken()